Pintushi\Bundle\OrganizationBundle\Entity\Organization:
    collectionOperations:
            post:
               denormalization_context:
                   groups: ["write"]
               validation_groups: ["pintushi"]
               access_control: is_granted('pintushi_organization_create')
               route_name: 'api_admin_create_organization'
            get:
               access_control: is_granted('pintushi_organization_view')
               relations:
                        - rel: create
                          access_controll: is_granted('pintushi_organization_create')
                          href:
                                route: api_organizations_post_collection
                                parameters:
                                    id: object.getId()
                        - rel: edit
                          access_controll: is_granted('pintushi_organization_edit', object)
                          href:
                                route: api_organizations_put_item
                                parameters:
                                    id: object.getId()
                        - rel: view
                          access_controll: is_granted('pintushi_organization_view', object)
                          href:
                                route: api_organizations_get_item
                                parameters:
                                    id: object.getId()
                        - rel: delete
                          access_controll: is_granted('pintushi_organization_delete')
                          href:
                                route: api_organizations_delete_item
                                parameters:
                                    id: object.getId()
    itemOperations:
            put:
               denormalization_context:
                   groups: ["write"]
               validation_groups: ["pintushi"]
               access_control: is_granted('pintushi_organization_edit', object)
               route_name: 'api_admin_update_organization'
            get:
               access_control: is_granted('pintushi_organization_view', object)
               relations:
                    - rel: create
                      access_controll: is_granted('pintushi_organization_create')
                      href:
                            route: api_organizations_post_collection
                            parameters:
                                id: object.getId()
                    - rel: edit
                      access_controll: is_granted('pintushi_organization_edit', object)
                      href:
                            route: api_organizations_put_item
                            parameters:
                                id: object.getId()
                    - rel: view
                      access_controll: is_granted('pintushi_organization_view', object)
                      href:
                            route: api_organizations_get_item
                            parameters:
                                id: object.getId()
                    - rel: delete
                      access_controll: is_granted('pintushi_organization_delete')
                      href:
                            route: api_organizations_delete_item
                            parameters:
                                id: object.getId()
            delete:
               access_control: is_granted('pintushi_organization_delete', object)
    attributes:
        normalization_context:
            groups: ["read", 'Details']
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin
