services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\OrganizationBundle\Form\Type\BusinessUnitSelectAutocomplete:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pintushi_organization.entity.business_unit.class%'
            - '@Pintushi\Bundle\OrganizationBundle\Entity\Manager\BusinessUnitManager'
        tags:
            - { name: form.type, alias: "pintushi_type_business_unit_select_autocomplete" }

    Pintushi\Bundle\OrganizationBundle\Form\Type\OrganizationsSelectType: ~

    Pintushi\Bundle\OrganizationBundle\Form\Type\OrganizationType:
        arguments:
            - '%pintushi_organization.entity.organization.class'
            - []
            - '@pintushi_organization.repository.organization'

    Pintushi\Bundle\OrganizationBundle\Form\Type\BusinessUnitType:
        arguments:
            - '%pintushi_organization.entity.business_unit.class'
            - []

    Pintushi\Bundle\OrganizationBundle\Form\Type\OrganizationProfileType:
        arguments:
            - '%pintushi_organization.entity.organization.class%'
            - []
