Pintushi\Bundle\OrganizationBundle\Entity\Organization:
    attributes:
        id:
            groups: ['read']
        name:
            groups: ['read', 'write']
        enabled:
            groups: ['Details', 'write']
        expiredAt:
            groups: ['Details', 'write']
        description:
            groups: ['read', 'write']
        address:
            groups: ['Details', 'write']
        logo:
            groups: ['Details', 'write']
        subdomain:
            groups: ['write']
        shippingMethods:
            groups: ['Details', 'write']
