api:
    resources:
        Pintushi\Bundle\OrganizationBundle\Entity\BusinessUnit:
            scope: pintushi_organization
            normalization_context:
                 groups: ["BusinessUnit"]
            validation_groups:  ["pintushi"]
            route_prefix: /admin
            form: 'Pintushi\Bundle\OrganizationBundle\Form\Type\BusinessUnitType'
            repository_class: 'Pintushi\Bundle\OrganizationBundle\Repository\BusinessUnitRepository'
            operations:
                create:
                    action: create
                    access_control: is_granted('pintushi_business_unit_create')
                create_form:
                    action: create
                    path: '/business_units/create-form'
                    methods: ['GET']
                    access_control: is_granted('pintushi_business_unit_create')
                index:
                    action: index
                    grid: business-unit-grid
                    access_control: is_granted('pintushi_business_unit_view')
                    normalization_context:
                       groups: ["Default", "BusinessUnit"]
                update:
                    action: update
                    access_control: is_granted('pintushi_business_unit_edit', object)
                update_form:
                    action: update
                    path: '/business_units/{id}/create-form'
                    access_control: is_granted('pintushi_business_unit_edit', object)
                view:
                    action: view
                    access_control: is_granted('pintushi_business_unit_view', object)
                delete:
                    action: delete
                    access_control: is_granted('pintushi_business_unit_delete', object)
