Pintushi\Bundle\OrganizationBundle\Entity\Organization:
    exclusion_policy: ALL
    xml_root_name: organization
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: ['Organization']
        name:
            expose: true
            type: string
            xml_attribute: true
            groups: ['Organization']
        enabled:
            expose: true
            type: boolean
            xml_attribute: true
            groups: ['Organization']
        global:
            expose: true
            type: boolean
            xml_attribute: true
            groups: ['Organization']
        expiredAt:
            expose: true
            type: DateTime
            xml_attribute: true
            groups: ['Organization']
        description:
            expose: true
            type: string
            xml_attribute: true
            groups: ['Organization']
        logo:
            expose: true
            type: string
            xml_attribute: true
            groups: ['Organization']
    relations:
        -   rel: view
            href:
                route: api_organizations_view
                parameters:
                    id: expr(object.getId())
            exclusion:
                groups: [Organization]
                exclude_if: "expr(!is_granted('pintushi_organization_view', object))"
        -   rel: update
            href:
                route: api_organizations_update
                parameters:
                    id: expr(object.getId())
            exclusion:
                groups: [Organization]
                exclude_if: "expr(!is_granted('pintushi_organization_update', object))"
        -   rel: delete
            href:
                route: api_organizations_delete
                parameters:
                    id: expr(object.getId())
            exclusion:
                groups: [Organization]
                exclude_if: "expr(!is_granted('pintushi_organization_delete', object))"
